#
# Copyright 2024, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[book]
title = "Using Rust in seL4 Userspace"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
multilingual = false
src = "src"

[build]
build-dir = "build"

[preprocessor.gh-links]
before = [ "links" ]

[output.html]
additional-css = ["preprocessor/gh-links.css"]
git-repository-url = "https://github.com/coliasgroup/rust-sel4-tutorial"
